"use client";

import { useState } from "react";
import { FileText, Download, Loader2 } from "lucide-react";
import { useToast } from "@/components/Toast";

interface InvoiceButtonProps {
  gigPda: string;
  gigTitle: string;
  clientWallet: string;
  freelancerWallet: string;
  totalBudget: string;
  releasedAmount: string;
  status: string;
  createdAt: string;
}

export function InvoiceButton({
  gigPda, gigTitle, clientWallet, freelancerWallet,
  totalBudget, releasedAmount, status, createdAt,
}: InvoiceButtonProps) {
  const [generating, setGenerating] = useState(false);
  const toast = useToast();

  const handleDownload = async () => {
    setGenerating(true);
    try {
      const params = new URLSearchParams({
        gigPda, title: gigTitle, client: clientWallet,
        freelancer: freelancerWallet, budget: totalBudget,
        released: releasedAmount, status, createdAt,
      });

      const res = await fetch(`/api/invoice?${params}`);
      if (!res.ok) throw new Error("Failed to generate invoice");
      
      const invoice = await res.json();
      
      // Generate downloadable text receipt
      const receipt = generateTextReceipt(invoice);
      
      // Download as file
      const blob = new Blob([receipt], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${invoice.invoiceNumber}-receipt.txt`;
      a.click();
      URL.revokeObjectURL(url);

      toast.success("Invoice downloaded!");
    } catch (err) {
      toast.error("Failed to generate invoice");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <button
      onClick={handleDownload}
      disabled={generating}
      className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg bg-white/5 border border-white/10 text-xs text-gray-400 hover:text-white hover:bg-white/10 transition disabled:opacity-50"
    >
      {generating ? (
        <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Generating...</>
      ) : (
        <><FileText className="w-3.5 h-3.5" /> Download Receipt</>
      )}
    </button>
  );
}

function generateTextReceipt(invoice: any): string {
  const line = "═".repeat(50);
  const divider = "─".repeat(50);

  return `
${line}
  GIGSAFE RECEIPT
  ${invoice.invoiceNumber}
${line}

Date:     ${new Date(invoice.date).toLocaleDateString("en-US", { 
    year: "numeric", month: "long", day: "numeric" 
  })}
Status:   ${invoice.status}

${divider}
GIG DETAILS
${divider}

Title:    ${invoice.gigTitle}
${invoice.description ? `Desc:     ${invoice.description}\n` : ""}${invoice.category ? `Category: ${invoice.category}\n` : ""}
Client:   ${invoice.client.name}
          ${invoice.client.wallet}

Freelancer: ${invoice.freelancer.name}
            ${invoice.freelancer.wallet}

${divider}
MILESTONES
${divider}

${invoice.milestones.length > 0 
  ? invoice.milestones.map((m: any, i: number) => `  ${i + 1}. ${m.name}`).join("\n")
  : "  No milestone details available"}

${divider}
FINANCIALS
${divider}

Total Budget:        ${invoice.financial.totalBudget.toFixed(2)} ${invoice.financial.currency}
Released:            ${invoice.financial.releasedAmount.toFixed(2)} ${invoice.financial.currency}
Platform Fee (0.5%): ${invoice.financial.platformFee.toFixed(2)} ${invoice.financial.currency}
Freelancer Received: ${invoice.financial.freelancerReceived.toFixed(2)} ${invoice.financial.currency}
Network:             ${invoice.financial.network}

${divider}
VERIFICATION
${divider}

Gig PDA:    ${invoice.gigPda}
Program:    ${invoice.verification.programId}
Explorer:   ${invoice.verification.explorerUrl}

${line}
  Generated by GigSafe — gigsafe.pixxmo.com
  Trustless Freelance Escrow on Solana
${line}
`.trim();
}
